# Generated by Django 3.2.8 on 2021-11-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicEntry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('UserGender', models.CharField(max_length=10)),
                ('UserPhone', models.CharField(max_length=13)),
                ('UserEmail', models.EmailField(max_length=254, unique=True)),
                ('UserPassword', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.district')),
            ],
        ),
        migrations.CreateModel(
            name='NewSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerName', models.CharField(max_length=50)),
                ('SeekerGender', models.CharField(max_length=10)),
                ('SeekerDob', models.CharField(max_length=20)),
                ('SeekerPhone', models.CharField(max_length=13)),
                ('SeekerEmail', models.EmailField(max_length=254, unique=True)),
                ('SeekerPassword', models.CharField(max_length=50)),
                ('PersonaldataStatus', models.CharField(default=0, max_length=5)),
                ('TestdataStatus', models.CharField(default=0, max_length=5)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.district')),
            ],
        ),
    ]
