# Generated by Django 3.2.10 on 2022-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseeker',
            name='longdrivestatus',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
