# Generated by Django 3.2.10 on 2022-02-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0002_newseeker_longdrivestatus'),
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintTitle', models.CharField(max_length=50)),
                ('ComplaintDetails', models.CharField(max_length=200)),
                ('Reply', models.CharField(max_length=200, null=True)),
                ('Status', models.BooleanField(default=False)),
                ('ComplaintDate', models.DateTimeField(auto_now=True)),
                ('ComplaintType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.complainttype')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
