# Generated by Django 3.2.8 on 2021-11-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintTypeName', models.CharField(max_length=50, unique=True, verbose_name='Complaint Type')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LongTravelingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LongTravelingPurposes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTravelingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageTravelingPurposes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestTypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestQuestions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortTravelingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortTravelingPurposes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceName', models.CharField(max_length=50)),
                ('DistrictName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.district')),
            ],
        ),
    ]
