# Generated by Django 3.2.8 on 2021-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0002_vehiclemodel_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DriveTypes', models.CharField(max_length=20)),
            ],
        ),
    ]
