# Generated by Django 3.2.8 on 2021-11-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0003_drivetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weeks', models.CharField(max_length=10)),
            ],
        ),
    ]
