# Generated by Django 3.2.8 on 2021-11-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0004_weekdays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekdays',
            new_name='Weekday',
        ),
    ]
