# Generated by Django 3.2.8 on 2021-11-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
        ('BasicEntry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongDriverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LongDriveLocation', models.CharField(max_length=30)),
                ('LongDriveStartDate', models.DateField(max_length=20)),
                ('LongDriveStartTime', models.TimeField(null=True)),
                ('LongDriveEndDate', models.DateField(max_length=20)),
                ('LongDriveEndTime', models.TimeField(null=True)),
                ('LongDriveBookingAmount', models.CharField(max_length=20)),
                ('LongDriveDistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.district')),
                ('LongDrivePurpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.longtravelingpurpose')),
                ('SeekerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShortDriverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortDriveBookingDate', models.DateField(max_length=30)),
                ('ShortDriveBookingTime', models.TimeField(null=True)),
                ('ShortDriveBookingDuration', models.CharField(max_length=10, null=True)),
                ('ShortDriveBookingLocation', models.CharField(max_length=20)),
                ('ShortDriveBookingAmount', models.CharField(max_length=20)),
                ('SeekerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
                ('ShortDrivePurpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.shorttravelingpurpose')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestAnswer', models.CharField(max_length=10)),
                ('SeekerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
                ('TestQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.seekertestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerLicenseNumber', models.CharField(max_length=50, unique=True)),
                ('SeekerLicenseProof', models.FileField(null=True, upload_to='Seeker/LicenseProof/')),
                ('SeekerAadharNumber', models.CharField(max_length=50, unique=True)),
                ('SeekerAadharProof', models.FileField(null=True, upload_to='Seeker/AadharProof/')),
                ('SeekerEyeTest', models.FileField(upload_to='Seeker/EyeTestProof/')),
                ('SeekerAdress', models.EmailField(max_length=50)),
                ('SeekerDisability', models.CharField(max_length=50)),
                ('SeekerDisabilityProof', models.FileField(null=True, upload_to='Seeker/DisabilityProof/')),
                ('SeekerBadge', models.CharField(max_length=50)),
                ('SeekerBadgeProof', models.FileField(null=True, upload_to='Seeker/BadgeProof/')),
                ('SeekerOffence', models.CharField(max_length=50)),
                ('SeekerRestriction', models.EmailField(max_length=50)),
                ('SeekerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
            ],
        ),
        
        migrations.CreateModel(
            name='LongTripDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LongDriveDay', models.CharField(max_length=5)),
                ('LongDriveLocation', models.CharField(max_length=30)),
                ('LongDriveStatus', models.CharField(max_length=10)),
                ('LongDriveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.longdriverbooking')),
            ],
        ),
    ]
