# Generated by Django 3.2.8 on 2021-11-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('Seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekertest',
            name='SeekerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker'),
        ),
    ]
