# Generated by Django 3.2.8 on 2021-12-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0004_auto_20211210_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDriveWorkingdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerShortDrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofileshortdrive')),
                ('WorkingDays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.weekday')),
            ],
        ),
    ]
