# Generated by Django 3.2.8 on 2021-12-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0006_longdriveworkingdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilelongdrive',
            name='LongDriveWorkingDays',
        ),
        migrations.RemoveField(
            model_name='seekerprofileshortdrive',
            name='ShortDriveWorkingDays',
        ),
    ]
