# Generated by Django 4.0 on 2021-12-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0007_auto_20211210_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofilelongdrive',
            name='LongDrivePurpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.longtravelingpurpose'),
        ),
    ]
