# Generated by Django 3.2.10 on 2021-12-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0008_alter_seekerprofilelongdrive_longdrivepurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintTitle', models.CharField(max_length=50)),
                ('ComplaintDetails', models.CharField(max_length=200)),
                ('Reply', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=10)),
                ('ComplaintDate', models.DateTimeField()),
                ('ComplaintType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.complainttype')),
                ('SeekerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
            ],
        ),
    ]
