# Generated by Django 3.2.10 on 2021-12-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0009_seekercomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekercomplaint',
            name='ComplaintDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seekercomplaint',
            name='Reply',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='seekercomplaint',
            name='Status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.CreateModel(
            name='LongDriveVehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerLongDrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofilelongdrive')),
                ('VehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.weekday')),
            ],
        ),
    ]
