# Generated by Django 3.2.10 on 2021-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0010_auto_20211216_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofilelongdrive',
            name='LongDriveEligibility',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
