# Generated by Django 3.2.10 on 2021-12-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0011_alter_seekerprofilelongdrive_longdriveeligibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilelongdrive',
            name='LongDriveVehicleModel',
        ),
    ]
