# Generated by Django 3.2.10 on 2021-12-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0012_remove_seekerprofilelongdrive_longdrivevehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longdrivevehiclemodels',
            name='VehicleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.vehiclemodel'),
        ),
    ]
