# Generated by Django 3.2.10 on 2021-12-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0013_alter_longdrivevehiclemodels_vehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofilepackage',
            name='PackageEligibility',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='PackageWorkingdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofilepackage')),
                ('WorkingDays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.weekday')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofilepackage')),
                ('VehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.vehiclemodel')),
            ],
        ),
    ]
