# Generated by Django 3.2.10 on 2021-12-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0018_auto_20211217_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofileshortdrive',
            name='ShortDrivePurpose',
        ),
        migrations.RemoveField(
            model_name='seekerprofileshortdrive',
            name='ShortDriveVehicleModel',
        ),
        migrations.CreateModel(
            name='ShortDriveVehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeekerLongDrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofileshortdrive')),
                ('VehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShortDrivePurposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purposes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.shorttravelingpurpose')),
                ('SeekerPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofileshortdrive')),
            ],
        ),
    ]
