# Generated by Django 3.2.10 on 2021-12-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0019_auto_20211220_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longdrivepurposes',
            old_name='SeekerPackage',
            new_name='SeekerLongDrive',
        ),
    ]
