# Generated by Django 3.2.10 on 2021-12-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0020_rename_seekerpackage_longdrivepurposes_seekerlongdrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortdrivepurposes',
            old_name='Purposes',
            new_name='ShortDrivePurposes',
        ),
    ]
