# Generated by Django 3.2.10 on 2021-12-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0021_rename_purposes_shortdrivepurposes_shortdrivepurposes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortdrivevehiclemodels',
            old_name='SeekerLongDrive',
            new_name='SeekerShortDrive',
        ),
    ]
