# Generated by Django 3.2.10 on 2021-12-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0023_rename_seekerpackage_shortdrivepurposes_seekershortdrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortdrivepurposes',
            old_name='ShortDrivePurposes',
            new_name='Purposes',
        ),
    ]
