# Generated by Django 3.2.10 on 2022-01-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('Seeker', '0026_alter_packagepurposes_seekerpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('TotalAmount', models.FloatField()),
                ('SeekerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newseeker')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
