# Generated by Django 3.2.10 on 2022-01-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0027_packagebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebooking',
            name='SeekerID',
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='SeekerPackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seeker.seekerprofilepackage'),
        ),
    ]
