# Generated by Django 3.2.10 on 2022-01-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicEntry', '0008_rename_drivehours_drivehour'),
        ('Seeker', '0028_auto_20220114_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortdriverbooking',
            name='SeekerID',
        ),
        migrations.RemoveField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingLocation',
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='Day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='Droptime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='Picktime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='Purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.packagetravelingpurpose'),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='Vehiclemodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='SeekerShortDriveid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofileshortdrive'),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingDropLocation',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingDropingTime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingIsReturn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingPickingDate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingPickingLocation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingPickingTime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
