# Generated by Django 3.2.10 on 2022-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0029_auto_20220124_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingDropLocation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
