# Generated by Django 3.2.10 on 2022-02-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0031_auto_20220124_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortdriverbooking',
            name='ShortDriveBookingDuration',
        ),
    ]
