# Generated by Django 3.2.10 on 2022-02-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0033_auto_20220207_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortdriverbooking',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
