# Generated by Django 3.2.10 on 2022-02-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0034_auto_20220208_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longdriverbooking',
            name='SeekerID',
        ),
        migrations.AddField(
            model_name='longdriverbooking',
            name='SeekerLongdrive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seeker.seekerprofilelongdrive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='longdriverbooking',
            name='LongDrivePurpose',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
