# Generated by Django 3.2.10 on 2022-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0035_auto_20220208_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='longdriverbooking',
            name='LongDriveVehicleModel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
