# Generated by Django 3.2.10 on 2022-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0037_packagebooking_moreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdriverbooking',
            name='moreinfo',
            field=models.TextField(default='No Data'),
        ),
    ]
