# Generated by Django 3.2.10 on 2022-02-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0039_auto_20220209_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='longdriverbooking',
            name='actualtotalamount',
            field=models.CharField(default='00.00', max_length=20),
        ),
        migrations.AddField(
            model_name='longdriverbooking',
            name='moreinfo',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='longdriverbooking',
            name='workcompletionremarks',
            field=models.CharField(default='No Remarks', max_length=20),
        ),
    ]
